# Generated by Django 4.2.4 on 2023-08-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('CUSTOMER', 'Customer'), ('BANKER', 'Banker'), ('PROVIDER', 'Provider')], default='STAFF', max_length=12, verbose_name='user type'),
        ),
    ]
