# Generated by Django 4.2.4 on 2023-08-08 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='budget')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('last_deposite', models.DateTimeField(auto_now=True, verbose_name='last_deposite')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'verbose_name': 'fund',
                'verbose_name_plural': 'funds',
                'db_table': 'funds',
            },
        ),
        migrations.CreateModel(
            name='FundTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='amount')),
                ('deposited_at', models.DateTimeField(auto_now_add=True, verbose_name='deposited at')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='funds.fund', verbose_name='fund')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fund_transactions', to=settings.AUTH_USER_MODEL, verbose_name='provider')),
            ],
            options={
                'verbose_name': 'fund transaction',
                'verbose_name_plural': 'fund transactions',
                'db_table': 'fund_transactions',
            },
        ),
    ]
