# Generated by Django 4.2.4 on 2023-08-09 16:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=15)),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='requested at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('amount', models.DecimalField(decimal_places=2, help_text='the loan amount', max_digits=10, validators=[django.core.validators.MinValueValidator(100, message='The minimum loan amount is 100')], verbose_name='amount')),
                ('term', models.PositiveIntegerField(help_text='number of months to pay the loan', verbose_name='loan term')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_requests', to=settings.AUTH_USER_MODEL, verbose_name='loan requester')),
            ],
            options={
                'verbose_name': 'loan request',
                'verbose_name_plural': 'loan requests',
                'db_table': 'loan_requests',
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(100, message='The minimum loan amount is 100')], verbose_name='loan principle amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1, message='interest rate can not be less than 1 (%)')], verbose_name='interest rate')),
                ('term', models.PositiveIntegerField(help_text='number of months to pay the loan', verbose_name='loan term')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='next loan payment date')),
                ('approved_at', models.DateTimeField(auto_now_add=True, verbose_name='approved at')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issued_loans', to=settings.AUTH_USER_MODEL, verbose_name='bank employee')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provided_loans', to=settings.AUTH_USER_MODEL, verbose_name='loan provider')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_loans', to=settings.AUTH_USER_MODEL, verbose_name='loan recipient')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loans.loanrequest', verbose_name='loan request')),
            ],
            options={
                'verbose_name': 'loan',
                'verbose_name_plural': 'loans',
                'db_table': 'loans',
            },
        ),
    ]
