# Generated by Django 4.2.4 on 2023-08-09 17:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(100, message='The minimum loan amount is 100')])),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='created at')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_transactions', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='loans.loan', verbose_name='loan')),
            ],
            options={
                'verbose_name': 'payment transaction',
                'verbose_name_plural': 'payment transactions',
                'db_table': 'payment_transactions',
            },
        ),
    ]
