# Generated by Django 4.2.4 on 2023-08-09 17:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_paymenttransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='no_payment',
            field=models.PositiveIntegerField(blank=True, help_text='number of payments to pay off the loan', null=True, verbose_name='number of payments'),
        ),
        migrations.AddField(
            model_name='loan',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(limit_value=1, message='interest rate can not be less than 1 (%)')], verbose_name='loan payment amount'),
        ),
        migrations.AddField(
            model_name='loan',
            name='yearly_interest_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1, message='interest rate can not be less than 1 (%)')], verbose_name='yearly interset rate'),
            preserve_default=False,
        ),
    ]
