# Generated by Django 4.2.4 on 2023-08-09 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_remove_loan_interest_rate_loan_no_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='no_payment',
        ),
    ]
