# Generated by Django 4.2.4 on 2023-08-09 17:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_remove_loan_no_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loan',
            name='yearly_interest_rate',
        ),
        migrations.AddField(
            model_name='loan',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, validators=[django.core.validators.MinValueValidator(limit_value=1, message='interest rate can not be less than 1 (%)')], verbose_name='annual interset rate'),
            preserve_default=False,
        ),
    ]
