# Generated by Django 4.2.4 on 2023-08-09 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='next loan payment date'),
        ),
    ]
